insert into Need (description, beneficiary_type,  jhi_date) values ('rutrum ac lobortis vel dapibus at diam nam tristique tortor', 'vestibulum quam sapien', '2018-03-19 22:53:20');
insert into Need (description, beneficiary_type,  jhi_date) values ('penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 'donec ut mauris eget', '2018-03-21 21:17:33');
insert into Need (description, beneficiary_type,  jhi_date) values ('morbi vel lectus in quam fringilla rhoncus mauris enim leo', 'nec dui luctus rutrum', '2017-12-23 20:14:03');
insert into Need (description, beneficiary_type,  jhi_date) values ('nullam sit amet turpis elementum ligula vehicula consequat morbi a', 'quisque erat eros', '2018-08-25 08:15:59');
insert into Need (description, beneficiary_type,  jhi_date) values ('eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 'at vulputate vitae', '2018-05-24 02:52:41');
insert into Need (description, beneficiary_type,  jhi_date) values ('ut massa volutpat convallis morbi odio odio elementum eu interdum', 'duis consequat dui nec', '2018-09-06 16:48:05');
insert into Need (description, beneficiary_type,  jhi_date) values ('ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent', 'donec dapibus duis at', '2017-10-02 19:14:47');
insert into Need (description, beneficiary_type,  jhi_date) values ('libero rutrum ac lobortis vel dapibus at diam nam tristique', 'a feugiat et eros', '2018-08-11 15:07:09');
insert into Need (description, beneficiary_type,  jhi_date) values ('lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 'rutrum nulla tellus in', '2018-08-09 16:14:45');
insert into Need (description, beneficiary_type,  jhi_date) values ('mauris enim leo rhoncus sed vestibulum sit amet cursus id', 'morbi non lectus', '2018-01-13 03:55:52');
insert into Need (description, beneficiary_type,  jhi_date) values ('vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 'potenti in eleifend', '2018-02-27 12:38:21');
insert into Need (description, beneficiary_type,  jhi_date) values ('suscipit a feugiat et eros vestibulum ac est lacinia nisi', 'magna vestibulum aliquet', '2018-07-08 06:32:09');
insert into Need (description, beneficiary_type,  jhi_date) values ('nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 'blandit lacinia erat', '2017-10-30 23:39:11');
insert into Need (description, beneficiary_type,  jhi_date) values ('varius integer ac leo pellentesque ultrices mattis odio donec vitae', 'ligula pellentesque ultrices phasellus', '2018-03-17 04:57:11');
insert into Need (description, beneficiary_type,  jhi_date) values ('nam nulla integer pede justo lacinia eget tincidunt eget tempus', 'in consequat ut nulla', '2018-01-12 22:33:20');
